ENERGIA_ENTRENAMIENTO = 20

MIN_AUMENTO_EXPERIENCIA = 2
MAX_AUMENTO_EXPERIENCIA = 56

MIN_AUMENTO_ENTRENAMIENTO = 6
MAX_AUMENTO_ENTRENAMIENTO= 78

AUMENTAR_VIDA_PLANTA = 5
AUMENTAR_ATAQUE_FUEGO = 3
AUMENTAR_VELOCIDAD_AGUA =8
ENERGIA_CREAR_OBJETO = 0

PROB_EXITO_OBJETO = 0

PROB_EXITO_BAYA = 1
GASTO_ENERGIA_BAYA = 5

PROB_EXITO_POCION = 3
GASTO_ENERGIA_POCION =5

AUMENTO_DEFENSA = 6
GASTO_ENERGIA_CARAMELO = 15
PROB_EXITO_CARAMELO = 7

